version = 0.1

[default.deploy.parameters]
stack_name = "plant-doctor-backend"
resolve_s3 = true
s3_prefix = "plant-doctor-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
image_repositories = []
