name: Deploy Plant Doctor

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # FRONTEND DEPLOYMENT
      - name: Build and push frontend
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          cd frontend
          docker build -t plant-doctor-frontend .
          docker tag plant-doctor-frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/plant-doctor-frontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/plant-doctor-frontend:latest
          cd ..
          
          
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster prod-plant-doctor-cluster --service prod-plant-doctor-frontend-svc --force-new-deployment
      
      # BACKEND DEPLOYMENT (LAMBDA)
      - name: Deploy Lambda backend
        run: |
          cd backend
          sam build --use-container
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          cd ..